services:
  node-1:
    build: .
    container_name: asteroidb-node-1
    cap_add:
      - NET_ADMIN
    ports:
      - "3001:3000"
    environment:
      ASTEROIDB_BIND_ADDR: "0.0.0.0:3000"
      ASTEROIDB_NODE_ID: "node-1"
      ASTEROIDB_INTERNAL_TOKEN: "${ASTEROIDB_INTERNAL_TOKEN:-changeme}"
    networks:
      - asteroidb

  node-2:
    build: .
    container_name: asteroidb-node-2
    cap_add:
      - NET_ADMIN
    ports:
      - "3002:3000"
    environment:
      ASTEROIDB_BIND_ADDR: "0.0.0.0:3000"
      ASTEROIDB_NODE_ID: "node-2"
      ASTEROIDB_INTERNAL_TOKEN: "${ASTEROIDB_INTERNAL_TOKEN:-changeme}"
    networks:
      - asteroidb

  node-3:
    build: .
    container_name: asteroidb-node-3
    cap_add:
      - NET_ADMIN
    ports:
      - "3003:3000"
    environment:
      ASTEROIDB_BIND_ADDR: "0.0.0.0:3000"
      ASTEROIDB_NODE_ID: "node-3"
      ASTEROIDB_INTERNAL_TOKEN: "${ASTEROIDB_INTERNAL_TOKEN:-changeme}"
    networks:
      - asteroidb

networks:
  asteroidb:
    driver: bridge
